import html
from fastapi import APIRouter,Request,HTTPException
from fastapi.responses import HTMLResponse
from app.storage import get_session,rows,one,utcnow
router=APIRouter()
def esc(v):return html.escape(str(v or ''))
def auth(r):
 s=get_session(r.cookies.get('gla_session'))
 if not s:raise HTTPException(401)
 return s
def n(sql,args=()):return one(sql,args)['n']
def money(rows_):return ' | '.join(format(float(x['amount'] or 0),',.2f')+' '+esc(x['currency']) for x in rows_) or '0'
def shell(b):return HTMLResponse('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CEO Command Center</title><style>body{font-family:Arial;background:#050f18;color:#edf7fb;margin:0}.w{max-width:1500px;margin:auto;padding:24px}.hero{padding:24px;background:linear-gradient(135deg,#102c3d,#0b1b28);border-radius:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin:14px 0}.k,.card{background:#102536;border:1px solid #28475d;border-radius:15px;padding:18px}.k b{display:block;font-size:25px;margin-top:8px}.card{margin:14px 0}.nav a{color:white;margin-left:13px}.red{color:#fca5a5}.amber{color:#fde68a}.green{color:#86efac}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #28475d;text-align:right}.btn{display:inline-block;padding:8px 11px;border-radius:8px;background:#22c55e;color:#04130a;text-decoration:none;font-weight:bold}.small{font-size:13px;color:#9fb4c4}</style><body><div class="w">'+b+'</div></body></html>')
def nav():return '<div class="nav"><a href="/ceo">CEO Command</a><a href="/sales-center">المبيعات</a><a href="/quotes">العروض</a><a href="/control-tower">Control Tower</a><a href="/operations">العمليات</a><a href="/dashboard">النظام</a></div>'
@router.get('/ceo')
def ceo(request:Request):
 auth(request);total=n("SELECT COUNT(*) n FROM opportunities WHERE stage<>'test'");won=n("SELECT COUNT(*) n FROM opportunities WHERE stage='won'");lost=n("SELECT COUNT(*) n FROM opportunities WHERE stage='lost'");openq=n("SELECT COUNT(*) n FROM sales_quotes WHERE status NOT IN ('client_accepted','rejected')");active=n("SELECT COUNT(*) n FROM shipments WHERE status NOT IN ('delivered','closed')");exceptions=n("SELECT COUNT(*) n FROM shipment_exceptions WHERE status='open'");overdue=n("SELECT COUNT(*) n FROM operations_tasks WHERE status='open' AND due_at<?",(utcnow(),));pending=n("SELECT COUNT(*) n FROM approvals WHERE status='pending'");winrate=round((won/(won+lost)*100),1) if won+lost else 0
 pipe=rows("SELECT currency,SUM(estimated_value) amount FROM opportunities WHERE stage NOT IN ('won','lost','test') GROUP BY currency");realized=rows("SELECT currency,SUM(realized_value) amount FROM sales_outcomes WHERE outcome='won' GROUP BY currency");profit=rows("SELECT s.currency,SUM(s.revenue-COALESCE(x.actual_cost,0)) amount FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id WHERE s.status IN ('delivered','closed') GROUP BY s.currency");dec=[]
 for x in rows("SELECT e.id,e.shipment_id,e.severity,e.summary,s.reference FROM shipment_exceptions e JOIN shipments s ON s.id=e.shipment_id WHERE e.status='open' ORDER BY CASE e.severity WHEN 'high' THEN 1 ELSE 2 END,e.created_at LIMIT 10"):dec.append(('تشغيل',x['severity'],x['reference'],x['summary'],'/control-tower/'+str(x['shipment_id'])))
 for x in rows("SELECT a.id,a.kind,a.entity_type,a.entity_id,a.notes FROM approvals a WHERE a.status='pending' ORDER BY a.created_at LIMIT 10"):dec.append(('اعتماد','medium',x['entity_type']+' #'+str(x['entity_id']),x.get('notes') or x['kind'],'/approvals'))
 for x in rows("SELECT t.id,t.shipment_id,t.title,t.owner,s.reference FROM operations_tasks t JOIN shipments s ON s.id=t.shipment_id WHERE t.status='open' AND t.due_at<? ORDER BY t.due_at LIMIT 10",(utcnow(),)):dec.append(('مهمة','high',x['reference'],x['title']+' — '+(x.get('owner') or 'غير مسند'),'/control-tower/'+str(x['shipment_id'])))
 dr=''.join('<tr><td>'+esc(x[0])+'</td><td class="'+('red' if x[1]=='high' else 'amber')+'">'+esc(x[1])+'</td><td>'+esc(x[2])+'</td><td>'+esc(x[3])+'</td><td><a class="btn" href="'+x[4]+'">فتح</a></td></tr>' for x in dec)
 stages=rows("SELECT stage,COUNT(*) n FROM opportunities WHERE stage<>'test' GROUP BY stage ORDER BY n DESC");sr=''.join('<tr><td>'+esc(x['stage'])+'</td><td>'+str(x['n'])+'</td></tr>' for x in stages);services=rows("SELECT service_type,COUNT(*) n,SUM(revenue) revenue,SUM(COALESCE(x.actual_cost,0)) cost,s.currency FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY service_type,s.currency ORDER BY n DESC");sv=''.join('<tr><td>'+esc(x['service_type'])+'</td><td>'+str(x['n'])+'</td><td>'+format(float(x['revenue'] or 0),',.2f')+' '+esc(x['currency'])+'</td><td>'+format(float(x['cost'] or 0),',.2f')+'</td><td>'+format(float(x['revenue'] or 0)-float(x['cost'] or 0),',.2f')+'</td></tr>' for x in services)
 return shell(nav()+'<div class="hero"><h1>CEO Command Center — آفاق طويق</h1><div class="small">صورة تنفيذية موحدة للمبيعات والإيرادات والعمليات والقرارات المطلوبة.</div></div><div class="grid"><div class="k">الفرص<b>'+str(total)+'</b></div><div class="k">Win Rate<b>'+str(winrate)+'%</b></div><div class="k">Pipeline<b>'+money(pipe)+'</b></div><div class="k">إيراد محقق<b>'+money(realized)+'</b></div><div class="k">ربح العمليات المغلقة<b>'+money(profit)+'</b></div><div class="k">عروض مفتوحة<b>'+str(openq)+'</b></div><div class="k">شحنات نشطة<b>'+str(active)+'</b></div><div class="k">Exceptions<b>'+str(exceptions)+'</b></div><div class="k">مهام متأخرة<b>'+str(overdue)+'</b></div><div class="k">اعتمادات معلقة<b>'+str(pending)+'</b></div></div><div class="card"><h2>تحتاج قرار الإدارة الآن</h2><table><tr><th>النوع</th><th>الأولوية</th><th>المرجع</th><th>الموضوع</th><th></th></tr>'+dr+'</table></div><div class="grid"><div class="card"><h2>قمع المبيعات</h2><table>'+sr+'</table></div><div class="card"><h2>الربحية حسب الخدمة</h2><table><tr><th>الخدمة</th><th>العمليات</th><th>الإيراد</th><th>التكلفة</th><th>الربح</th></tr>'+sv+'</table></div></div>')
@router.get('/api/v7/ceo')
def api(request:Request):
 auth(request);return {'sales_funnel':rows("SELECT stage,COUNT(*) count,currency,SUM(estimated_value) value FROM opportunities WHERE stage<>'test' GROUP BY stage,currency"),'revenue':rows("SELECT currency,SUM(realized_value) realized FROM sales_outcomes WHERE outcome='won' GROUP BY currency"),'operations':rows("SELECT COALESCE(x.stage,s.status) stage,COUNT(*) count FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY COALESCE(x.stage,s.status)"),'exceptions':rows("SELECT kind,severity,COUNT(*) count FROM shipment_exceptions WHERE status='open' GROUP BY kind,severity")}
