import html,urllib.parse,datetime
from fastapi import APIRouter,Request,HTTPException
from fastapi.responses import HTMLResponse,RedirectResponse
from app.storage import get_session,rows,one,execute,log,utcnow
router=APIRouter()
SLA={'new':24,'documents':24,'customs_clearance':48,'customs_released':12,'pickup':12,'in_transit':72,'warehouse':48,'out_for_delivery':24}
def esc(v):return html.escape(str(v or ''))
def auth(r):
 s=get_session(r.cookies.get('gla_session'))
 if not s:raise HTTPException(401)
 return s
def parse(raw):return {k:v[0] for k,v in urllib.parse.parse_qs(raw.decode()).items()}
def shell(b):return HTMLResponse('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#06121d;color:#eef6fb;margin:0}.w{max-width:1400px;margin:auto;padding:24px}.card{background:#102536;border:1px solid #28475d;border-radius:16px;padding:18px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.k{background:#0b1d2b;padding:18px;border-radius:12px}.k b{display:block;font-size:25px;margin-top:8px}.btn{display:inline-block;padding:9px 12px;border:0;border-radius:9px;background:#22c55e;color:#04130a;text-decoration:none;font-weight:bold}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #28475d;text-align:right}.red{color:#fca5a5}.amber{color:#fde68a}.green{color:#86efac}.nav a{color:white;margin-left:12px}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;margin:5px 0;background:#081925;color:white;border:1px solid #36586e;border-radius:8px}</style><body><div class="w">'+b+'</div></body></html>')
def nav():return '<div class="nav"><a href="/control-tower">Control Tower</a><a href="/operations">العمليات</a><a href="/sales-center">المبيعات</a><a href="/dashboard">الرئيسية</a></div>'
def refresh_exceptions(uid):
 now=utcnow();ops=rows("SELECT s.id shipment_id,s.reference,s.status,x.stage,x.eta,x.updated_at FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id WHERE s.status NOT IN ('delivered','closed')")
 for x in ops:
  stage=x.get('stage') or x['status'];updated=x.get('updated_at');hours=SLA.get(stage)
  if x.get('eta') and x['eta']<now:execute("INSERT INTO shipment_exceptions(shipment_id,kind,severity,status,summary,created_at,updated_at) SELECT ?,?,'high','open',?,?,? WHERE NOT EXISTS(SELECT 1 FROM shipment_exceptions WHERE shipment_id=? AND kind=? AND status='open')",(x['shipment_id'],'eta_delay','ETA exceeded',now,now,x['shipment_id'],'eta_delay'))
  if hours and updated and updated+datetime.timedelta(hours=hours)<now:execute("INSERT INTO shipment_exceptions(shipment_id,kind,severity,status,summary,created_at,updated_at) SELECT ?,?,'medium','open',?,?,? WHERE NOT EXISTS(SELECT 1 FROM shipment_exceptions WHERE shipment_id=? AND kind=? AND status='open')",(x['shipment_id'],'sla_breach','SLA exceeded for '+stage,now,now,x['shipment_id'],'sla_breach'))
@router.get('/control-tower')
def tower(request:Request):
 u=auth(request);refresh_exceptions(u['user_id']);active=one("SELECT COUNT(*) n FROM shipments WHERE status NOT IN ('delivered','closed')")['n'];exc=one("SELECT COUNT(*) n FROM shipment_exceptions WHERE status='open'")['n'];late=one("SELECT COUNT(*) n FROM shipment_exceptions WHERE status='open' AND kind='eta_delay'")['n'];tasks=one("SELECT COUNT(*) n FROM operations_tasks WHERE status='open'")['n'];es=rows("SELECT e.*,s.reference,x.customs_port FROM shipment_exceptions e JOIN shipments s ON s.id=e.shipment_id LEFT JOIN shipment_operations x ON x.shipment_id=s.id WHERE e.status='open' ORDER BY CASE e.severity WHEN 'high' THEN 1 ELSE 2 END,e.created_at");etr=''.join('<tr><td>'+esc(x['reference'])+'</td><td>'+esc(x.get('customs_port') or '—')+'</td><td class="'+('red' if x['severity']=='high' else 'amber')+'">'+esc(x['severity'])+'</td><td>'+esc(x['summary'])+'</td><td><a class="btn" href="/control-tower/'+str(x['shipment_id'])+'">معالجة</a></td></tr>' for x in es);ports=rows("SELECT COALESCE(x.customs_port,'غير محدد') port,COUNT(*) shipments,COALESCE(SUM(s.revenue),0) revenue,COALESCE(SUM(x.actual_cost),0) cost,s.currency FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY COALESCE(x.customs_port,'غير محدد'),s.currency ORDER BY shipments DESC");pr=''.join('<tr><td>'+esc(x['port'])+'</td><td>'+str(x['shipments'])+'</td><td>'+format(float(x['revenue']),',.2f')+' '+esc(x['currency'])+'</td><td>'+format(float(x['cost']),',.2f')+'</td><td>'+format(float(x['revenue'])-float(x['cost']),',.2f')+'</td></tr>' for x in ports)
 return shell(nav()+'<h1>Afaaq Tuwaiq Operations Control Tower</h1><div class="grid"><div class="k">عمليات نشطة<b>'+str(active)+'</b></div><div class="k">Exceptions مفتوحة<b>'+str(exc)+'</b></div><div class="k">تأخير ETA<b>'+str(late)+'</b></div><div class="k">مهام تشغيلية<b>'+str(tasks)+'</b></div></div><div class="card"><h2>التنبيهات والاستثناءات</h2><table><tr><th>الشحنة</th><th>المنفذ</th><th>الخطورة</th><th>التنبيه</th><th></th></tr>'+etr+'</table></div><div class="card"><h2>الربحية حسب المنفذ</h2><table><tr><th>المنفذ</th><th>العمليات</th><th>الإيراد</th><th>التكلفة</th><th>الربح</th></tr>'+pr+'</table></div>')
@router.get('/control-tower/{sid}')
def shipment(sid:int,request:Request):
 auth(request);s=one('SELECT s.*,x.stage,x.customs_port,x.eta,x.carrier FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id WHERE s.id=?',(sid,));
 if not s:raise HTTPException(404)
 ev=rows('SELECT * FROM shipment_events WHERE shipment_id=? ORDER BY happened_at DESC,id DESC',(sid,));tasks=rows('SELECT * FROM operations_tasks WHERE shipment_id=? ORDER BY due_at,id DESC',(sid,));ex=rows('SELECT * FROM shipment_exceptions WHERE shipment_id=? ORDER BY id DESC',(sid,));er=''.join('<tr><td>'+esc(x['happened_at'])+'</td><td>'+esc(x['event_type'])+'</td><td>'+esc(x['summary'])+'</td></tr>' for x in ev);tr=''.join('<tr><td>'+esc(x['title'])+'</td><td>'+esc(x['owner'])+'</td><td>'+esc(x['due_at'])+'</td><td>'+esc(x['status'])+'</td></tr>' for x in tasks);xr=''.join('<tr><td>'+esc(x['kind'])+'</td><td>'+esc(x['severity'])+'</td><td>'+esc(x['summary'])+'</td><td>'+esc(x['status'])+'</td><td>'+('<form method="post" action="/control-tower/exception/'+str(x['id'])+'/resolve"><button class="btn">حل</button></form>' if x['status']=='open' else '')+'</td></tr>' for x in ex)
 return shell(nav()+'<h1>'+esc(s['reference'])+' — Control Tower</h1><div class="card"><h2>إضافة مهمة تشغيلية</h2><form method="post" action="/control-tower/'+str(sid)+'/task"><div class="grid"><input name="title" required placeholder="المهمة"><input name="owner" placeholder="الموظف/الفريق"><input type="datetime-local" name="due_at" required></div><textarea name="notes" placeholder="التفاصيل"></textarea><button class="btn">إضافة المهمة</button></form><table><tr><th>المهمة</th><th>المسؤول</th><th>الموعد</th><th>الحالة</th></tr>'+tr+'</table></div><div class="card"><h2>Exceptions</h2><table>'+xr+'</table></div><div class="card"><h2>Timeline</h2><table><tr><th>الوقت</th><th>الحدث</th><th>التفاصيل</th></tr>'+er+'</table></div>')
@router.post('/control-tower/{sid}/task')
async def task(sid:int,request:Request):
 u=auth(request);d=parse(await request.body());
 try:due=datetime.datetime.fromisoformat(d['due_at']).replace(tzinfo=datetime.timezone(datetime.timedelta(hours=3)))
 except:raise HTTPException(400,'Invalid due date')
 tid=execute('INSERT INTO operations_tasks(shipment_id,title,owner,due_at,status,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)',(sid,d.get('title'),d.get('owner'),due,'open',d.get('notes'),u['user_id'],utcnow()));log(u['user_id'],'operations_task','operations_task',tid,'Operations task created');return RedirectResponse('/control-tower/'+str(sid),303)
@router.post('/control-tower/exception/{eid}/resolve')
def resolve(eid:int,request:Request):
 u=auth(request);e=one('SELECT * FROM shipment_exceptions WHERE id=?',(eid,));
 if not e:raise HTTPException(404)
 execute("UPDATE shipment_exceptions SET status='resolved',resolved_by=?,resolved_at=?,updated_at=? WHERE id=?",(u['user_id'],utcnow(),utcnow(),eid));log(u['user_id'],'resolve_exception','shipment_exception',eid,'Exception resolved');return RedirectResponse('/control-tower/'+str(e['shipment_id']),303)
@router.get('/api/v7/control-tower')
def api(request:Request):
 auth(request);return {'exceptions':rows("SELECT kind,severity,COUNT(*) count FROM shipment_exceptions WHERE status='open' GROUP BY kind,severity"),'profitability':rows("SELECT s.currency,SUM(s.revenue) revenue,SUM(COALESCE(x.actual_cost,0)) actual_cost,SUM(s.revenue-COALESCE(x.actual_cost,0)) profit FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY s.currency"),'stages':rows("SELECT COALESCE(x.stage,s.status) stage,COUNT(*) count FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY COALESCE(x.stage,s.status)")}
