import html
from fastapi import APIRouter,Request,HTTPException
from fastapi.responses import HTMLResponse
from app.storage import get_session,rows,one
router=APIRouter()
def e(v):return html.escape(str(v or ''))
def auth(r):
 s=get_session(r.cookies.get('gla_session'))
 if not s:raise HTTPException(401)
 return s
def shell(b):return HTMLResponse('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#06121d;color:#eef6fb;margin:0}.w{max-width:1450px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.card,.k{background:#102536;border:1px solid #28475d;border-radius:15px;padding:18px;margin:12px 0}.k b{display:block;font-size:24px;margin-top:8px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #28475d;text-align:right}a{color:#dff6ff}.btn{padding:8px 11px;border-radius:8px;background:#22c55e;color:#04130a;text-decoration:none;font-weight:bold}.nav a{margin-left:12px;color:white}.muted{color:#9fb4c4}.green{color:#86efac}.amber{color:#fde68a}.red{color:#fca5a5}</style><body><div class="w">'+b+'</div></body></html>')
def nav():return '<div class="nav"><a href="/customers360">Customer 360</a><a href="/ceo">CEO Command</a><a href="/sales-center">المبيعات</a><a href="/control-tower">العمليات</a></div>'
def customers():return rows("""SELECT a.id,a.name,a.country,COUNT(DISTINCT o.id) opportunities,COUNT(DISTINCT s.id) shipments,COUNT(DISTINCT CASE WHEN o.stage='won' THEN o.id END) won,COUNT(DISTINCT CASE WHEN o.stage='lost' THEN o.id END) lost FROM accounts a LEFT JOIN opportunities o ON o.account_id=a.id LEFT JOIN shipments s ON s.account_id=a.id GROUP BY a.id,a.name,a.country ORDER BY shipments DESC,won DESC,a.name""")
@router.get('/customers360')
def index(request:Request):
 auth(request);cs=customers();tr=''.join('<tr><td><a href="/customers360/'+str(x['id'])+'">'+e(x['name'])+'</a></td><td>'+e(x['country'])+'</td><td>'+str(x['opportunities'])+'</td><td>'+str(x['won'])+'</td><td>'+str(x['shipments'])+'</td><td><a class="btn" href="/customers360/'+str(x['id'])+'">360°</a></td></tr>' for x in cs);top=rows("""SELECT a.id,a.name,s.currency,SUM(s.revenue) revenue,SUM(COALESCE(x.actual_cost,0)) cost,SUM(s.revenue-COALESCE(x.actual_cost,0)) profit,COUNT(*) jobs FROM accounts a JOIN shipments s ON s.account_id=a.id LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY a.id,a.name,s.currency ORDER BY profit DESC LIMIT 20""");pr=''.join('<tr><td><a href="/customers360/'+str(x['id'])+'">'+e(x['name'])+'</a></td><td>'+str(x['jobs'])+'</td><td>'+format(float(x['revenue'] or 0),',.2f')+' '+e(x['currency'])+'</td><td>'+format(float(x['profit'] or 0),',.2f')+'</td></tr>' for x in top)
 return shell(nav()+'<h1>Customer 360 + Profitability Intelligence</h1><p class="muted">رؤية موحدة للعميل من أول فرصة حتى الربحية التشغيلية.</p><div class="card"><h2>العملاء</h2><table><tr><th>العميل</th><th>الدولة</th><th>الفرص</th><th>Won</th><th>العمليات</th><th></th></tr>'+tr+'</table></div><div class="card"><h2>العملاء حسب الربحية</h2><table><tr><th>العميل</th><th>العمليات</th><th>الإيراد</th><th>الربح التشغيلي</th></tr>'+pr+'</table></div>')
@router.get('/customers360/{aid}')
def detail(aid:int,request:Request):
 auth(request);a=one('SELECT * FROM accounts WHERE id=?',(aid,));
 if not a:raise HTTPException(404)
 opp=rows('SELECT * FROM opportunities WHERE account_id=? ORDER BY id DESC',(aid,));ships=rows('SELECT s.*,x.actual_cost,x.stage ops_stage,x.customs_port FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id WHERE s.account_id=? ORDER BY s.id DESC',(aid,));quotes=rows('SELECT q.* FROM sales_quotes q JOIN opportunities o ON o.id=q.opportunity_id WHERE o.account_id=? ORDER BY q.id DESC',(aid,));msgs=rows('SELECT m.* FROM outbound_messages m JOIN opportunities o ON o.id=m.opportunity_id WHERE o.account_id=? ORDER BY m.id DESC LIMIT 30',(aid,));replies=rows('SELECT r.* FROM inbound_replies r JOIN opportunities o ON o.id=r.opportunity_id WHERE o.account_id=? ORDER BY r.id DESC LIMIT 30',(aid,));curr={}
 for s in ships:
  c=s['currency'];d=curr.setdefault(c,{'rev':0,'cost':0,'jobs':0});d['rev']+=float(s['revenue'] or 0);d['cost']+=float(s.get('actual_cost') or 0);d['jobs']+=1
 fin=''.join('<div class="k">'+e(c)+'<b>'+format(v['rev'],',.2f')+' Revenue</b><span>Profit '+format(v['rev']-v['cost'],',.2f')+' | '+str(v['jobs'])+' عمليات</span></div>' for c,v in curr.items()) or '<div class="k">لا توجد عمليات مالية بعد</div>';won=sum(1 for x in opp if x['stage']=='won');lost=sum(1 for x in opp if x['stage']=='lost');rate=round(won/(won+lost)*100,1) if won+lost else 0;repeat=len(ships);orows=''.join('<tr><td>'+str(x['id'])+'</td><td>'+e(x['signal'])+'</td><td>'+e(x['stage'])+'</td><td>'+str(x['score'])+'</td><td>'+format(float(x['estimated_value'] or 0),',.2f')+' '+e(x['currency'])+'</td></tr>' for x in opp);srows=''.join('<tr><td><a href="/operations/'+str(x['id'])+'">'+e(x['reference'])+'</a></td><td>'+e(x['service_type'])+'</td><td>'+e(x.get('customs_port') or '—')+'</td><td>'+e(x.get('ops_stage') or x['status'])+'</td><td>'+format(float(x['revenue'] or 0),',.2f')+'</td><td>'+format(float(x.get('actual_cost') or 0),',.2f')+'</td><td>'+format(float(x['revenue'] or 0)-float(x.get('actual_cost') or 0),',.2f')+'</td></tr>' for x in ships);qrows=''.join('<tr><td>'+e(x['quote_number'])+'</td><td>'+e(x['service_type'])+'</td><td>'+e(x['status'])+'</td><td>'+format(float(x['sell_price'] or 0),',.2f')+' '+e(x['currency'])+'</td></tr>' for x in quotes);timeline=[]
 for x in msgs:timeline.append((x.get('created_at'),'Outbound',x.get('subject') or '',x.get('status')))
 for x in replies:timeline.append((x.get('received_at') or x.get('created_at'),'Inbound',x.get('subject') or '',x.get('classification')))
 timeline.sort(key=lambda z:str(z[0]),reverse=True);tl=''.join('<tr><td>'+e(x[0])+'</td><td>'+e(x[1])+'</td><td>'+e(x[2])+'</td><td>'+e(x[3])+'</td></tr>' for x in timeline[:40])
 services={}
 for s in ships:
  key=(s['service_type'],s['currency']);d=services.setdefault(key,[0,0,0]);d[0]+=1;d[1]+=float(s['revenue'] or 0);d[2]+=float(s.get('actual_cost') or 0)
 best=sorted(services.items(),key=lambda z:z[1][1]-z[1][2],reverse=True);sv=''.join('<tr><td>'+e(k[0])+'</td><td>'+str(v[0])+'</td><td>'+format(v[1]-v[2],',.2f')+' '+e(k[1])+'</td></tr>' for k,v in best)
 return shell(nav()+'<h1>'+e(a['name'])+' — Customer 360</h1><div class="grid"><div class="k">الفرص<b>'+str(len(opp))+'</b></div><div class="k">Win Rate<b>'+str(rate)+'%</b></div><div class="k">تكرار العمليات<b>'+str(repeat)+'</b></div><div class="k">العروض<b>'+str(len(quotes))+'</b></div>'+fin+'</div><div class="card"><h2>ربحية الخدمات لهذا العميل</h2><table><tr><th>الخدمة</th><th>العمليات</th><th>الربح</th></tr>'+sv+'</table></div><div class="card"><h2>العمليات والشحنات</h2><table><tr><th>المرجع</th><th>الخدمة</th><th>المنفذ</th><th>الحالة</th><th>الإيراد</th><th>التكلفة</th><th>الربح</th></tr>'+srows+'</table></div><div class="card"><h2>الفرص</h2><table><tr><th>ID</th><th>الإشارة</th><th>المرحلة</th><th>Score</th><th>القيمة</th></tr>'+orows+'</table></div><div class="card"><h2>العروض</h2><table><tr><th>العرض</th><th>الخدمة</th><th>الحالة</th><th>القيمة</th></tr>'+qrows+'</table></div><div class="card"><h2>Timeline التواصل</h2><table><tr><th>الوقت</th><th>الاتجاه</th><th>الموضوع</th><th>الحالة/النية</th></tr>'+tl+'</table></div>')
@router.get('/api/v7/customers360')
def api(request:Request):
 auth(request);return {'customers':customers(),'profitability':rows("SELECT a.id,a.name,s.currency,SUM(s.revenue) revenue,SUM(COALESCE(x.actual_cost,0)) actual_cost,SUM(s.revenue-COALESCE(x.actual_cost,0)) profit,COUNT(*) shipments FROM accounts a JOIN shipments s ON s.account_id=a.id LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY a.id,a.name,s.currency ORDER BY profit DESC")}
