import html,urllib.parse,datetime
from fastapi import APIRouter,Request,HTTPException
from fastapi.responses import HTMLResponse,RedirectResponse
from app.storage import get_session,rows,one,execute,log,utcnow
router=APIRouter()
def esc(v):return html.escape(str(v or ''))
def auth(r):
 s=get_session(r.cookies.get('gla_session'))
 if not s:raise HTTPException(401)
 return s
def parse(raw):return {k:v[0] for k,v in urllib.parse.parse_qs(raw.decode()).items()}
def shell(b):return HTMLResponse('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#07131f;color:#eef6fb;margin:0}.w{max-width:1350px;margin:auto;padding:24px}.card{background:#102536;border:1px solid #28475d;border-radius:16px;padding:18px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.k{background:#0b1d2b;padding:18px;border-radius:12px}.k b{display:block;font-size:24px;margin-top:8px}.btn{display:inline-block;padding:9px 12px;border:0;border-radius:9px;background:#22c55e;color:#04130a;text-decoration:none;font-weight:bold;cursor:pointer}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;margin:5px 0;background:#081925;color:white;border:1px solid #36586e;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-bottom:1px solid #28475d;text-align:right}.muted{color:#9fb4c4}.nav a{color:white;margin-left:12px}.bad{color:#fca5a5}.good{color:#86efac}</style><body><div class="w">'+b+'</div></body></html>')
def nav():return '<div class="nav"><a href="/operations">مركز العمليات</a><a href="/sales-center">المبيعات</a><a href="/quote-workflow">العروض</a><a href="/shipments">الشحنات</a><a href="/dashboard">الرئيسية</a></div>'
@router.get('/operations')
def home(request:Request):
 auth(request);data=rows("SELECT s.*,x.customs_port,x.carrier,x.driver_name,x.vehicle_plate,x.eta,x.actual_cost,x.stage ops_stage FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id ORDER BY s.id DESC LIMIT 200");active=sum(1 for x in data if x['status'] not in ('delivered','closed'));delayed=sum(1 for x in data if x.get('eta') and x['eta']<utcnow() and x['status'] not in ('delivered','closed'));trs=''.join('<tr><td><a style="color:white" href="/operations/'+str(x['id'])+'">'+esc(x['reference'])+'</a></td><td>'+esc(x['service_type'])+'</td><td>'+esc(x.get('customs_port') or '—')+'</td><td>'+esc(x.get('ops_stage') or x['status'])+'</td><td>'+esc(x.get('eta') or '—')+'</td><td>'+esc(x['revenue'])+' '+esc(x['currency'])+'</td><td>'+esc(x.get('actual_cost') or x['cost'])+'</td></tr>' for x in data);return shell(nav()+'<h1>Operations Control Center — آفاق طويق</h1><div class="grid"><div class="k">الشحنات<b>'+str(len(data))+'</b></div><div class="k">نشطة<b>'+str(active)+'</b></div><div class="k">متجاوزة ETA<b>'+str(delayed)+'</b></div></div><div class="card"><table><tr><th>المرجع</th><th>الخدمة</th><th>المنفذ</th><th>المرحلة</th><th>ETA</th><th>الإيراد</th><th>التكلفة الفعلية</th></tr>'+trs+'</table></div>')
@router.get('/operations/{sid}')
def detail(sid:int,request:Request):
 auth(request);s=one('SELECT * FROM shipments WHERE id=?',(sid,));
 if not s:raise HTTPException(404)
 x=one('SELECT * FROM shipment_operations WHERE shipment_id=?',(sid,)) or {};docs=rows('SELECT * FROM shipment_documents WHERE shipment_id=? ORDER BY id DESC',(sid,));actual=float(x.get('actual_cost') or 0);revenue=float(s['revenue'] or 0);profit=revenue-actual if actual else None;dr=''.join('<tr><td>'+esc(d['document_type'])+'</td><td>'+esc(d['document_ref'])+'</td><td>'+esc(d['status'])+'</td><td>'+esc(d['notes'])+'</td></tr>' for d in docs)
 b=nav()+'<h1>'+esc(s['reference'])+'</h1><div class="grid"><div class="k">الحالة<b>'+esc(x.get('stage') or s['status'])+'</b></div><div class="k">الإيراد<b>'+esc(s['revenue'])+' '+esc(s['currency'])+'</b></div><div class="k">التكلفة الفعلية<b>'+esc(actual)+' '+esc(s['currency'])+'</b></div><div class="k">الربح الفعلي<b>'+((format(profit,',.2f')+' '+esc(s['currency'])) if profit is not None else 'بانتظار التكلفة')+'</b></div></div><div class="card"><h2>بيانات التشغيل</h2><form method="post" action="/operations/'+str(sid)+'/update"><div class="grid"><select name="stage"><option>'+esc(x.get('stage') or s['status'])+'</option><option>new</option><option>documents</option><option>customs_clearance</option><option>customs_released</option><option>pickup</option><option>in_transit</option><option>warehouse</option><option>out_for_delivery</option><option>delivered</option><option>closed</option></select><input name="customs_port" value="'+esc(x.get('customs_port'))+'" placeholder="المنفذ الجمركي"><input name="carrier" value="'+esc(x.get('carrier'))+'" placeholder="الناقل"><input name="driver_name" value="'+esc(x.get('driver_name'))+'" placeholder="السائق"><input name="driver_phone" value="'+esc(x.get('driver_phone'))+'" placeholder="هاتف السائق"><input name="vehicle_plate" value="'+esc(x.get('vehicle_plate'))+'" placeholder="لوحة المركبة"><input type="datetime-local" name="eta" placeholder="ETA"><input type="number" step="0.01" min="0" name="actual_cost" value="'+esc(x.get('actual_cost') or 0)+'" placeholder="التكلفة الفعلية"></div><textarea name="notes" placeholder="ملاحظات التشغيل">'+esc(x.get('notes'))+'</textarea><button class="btn">حفظ تحديث التشغيل</button></form></div><div class="card"><h2>المستندات</h2><form method="post" action="/operations/'+str(sid)+'/document"><div class="grid"><select name="document_type"><option>commercial_invoice</option><option>packing_list</option><option>bill_of_lading</option><option>certificate_of_origin</option><option>customs_declaration</option><option>delivery_note</option><option>other</option></select><input name="document_ref" placeholder="رقم/مرجع المستند"><select name="status"><option>received</option><option>pending</option><option>verified</option><option>missing</option></select></div><input name="notes" placeholder="ملاحظات"><button class="btn">إضافة المستند</button></form><table><tr><th>المستند</th><th>المرجع</th><th>الحالة</th><th>ملاحظات</th></tr>'+dr+'</table></div>'
 return shell(b)
@router.post('/operations/{sid}/update')
async def update(sid:int,request:Request):
 u=auth(request);d=parse(await request.body());stage=d.get('stage','new');allowed={'new','documents','customs_clearance','customs_released','pickup','in_transit','warehouse','out_for_delivery','delivered','closed'}
 if stage not in allowed:raise HTTPException(400,'Invalid stage')
 eta=None
 if d.get('eta'):
  try:eta=datetime.datetime.fromisoformat(d['eta']).replace(tzinfo=datetime.timezone(datetime.timedelta(hours=3)))
  except:raise HTTPException(400,'Invalid ETA')
 cost=float(d.get('actual_cost') or 0);now=utcnow();execute('INSERT INTO shipment_operations(shipment_id,stage,customs_port,carrier,driver_name,driver_phone,vehicle_plate,eta,actual_cost,notes,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(shipment_id) DO UPDATE SET stage=EXCLUDED.stage,customs_port=EXCLUDED.customs_port,carrier=EXCLUDED.carrier,driver_name=EXCLUDED.driver_name,driver_phone=EXCLUDED.driver_phone,vehicle_plate=EXCLUDED.vehicle_plate,eta=EXCLUDED.eta,actual_cost=EXCLUDED.actual_cost,notes=EXCLUDED.notes,updated_by=EXCLUDED.updated_by,updated_at=EXCLUDED.updated_at',(sid,stage,d.get('customs_port'),d.get('carrier'),d.get('driver_name'),d.get('driver_phone'),d.get('vehicle_plate'),eta,cost,d.get('notes'),u['user_id'],now,now));execute('UPDATE shipments SET status=?,cost=?,updated_at=? WHERE id=?',(stage,cost,now,sid));log(u['user_id'],'shipment_ops_update','shipment',sid,'Operations stage -> '+stage);return RedirectResponse('/operations/'+str(sid),303)
@router.post('/operations/{sid}/document')
async def document(sid:int,request:Request):
 u=auth(request);d=parse(await request.body());did=execute('INSERT INTO shipment_documents(shipment_id,document_type,document_ref,status,notes,created_by,created_at) VALUES(?,?,?,?,?,?,?)',(sid,d.get('document_type','other'),d.get('document_ref'),d.get('status','received'),d.get('notes'),u['user_id'],utcnow()));log(u['user_id'],'shipment_document','shipment_document',did,'Shipment document registered');return RedirectResponse('/operations/'+str(sid),303)
@router.get('/api/v7/operations')
def api(request:Request):
 auth(request);return {'shipments':rows('SELECT s.*,x.stage ops_stage,x.customs_port,x.carrier,x.eta,x.actual_cost FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id ORDER BY s.id DESC'),'stages':rows('SELECT COALESCE(x.stage,s.status) stage,COUNT(*) count FROM shipments s LEFT JOIN shipment_operations x ON x.shipment_id=s.id GROUP BY COALESCE(x.stage,s.status)')}
