import html,urllib.parse
from fastapi import APIRouter,Request,HTTPException
from fastapi.responses import HTMLResponse,RedirectResponse
from app.storage import get_session,rows,one,execute,log,utcnow
router=APIRouter()
def esc(v):return html.escape(str(v or ''))
def auth(r):
 s=get_session(r.cookies.get('gla_session'))
 if not s:raise HTTPException(401)
 return s
def parse(raw):return {k:v[0] for k,v in urllib.parse.parse_qs(raw.decode()).items()}
def shell(b):return HTMLResponse('<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial;background:#07131f;color:#eef6fb;margin:0}.w{max-width:1200px;margin:auto;padding:24px}.card{background:#102536;border:1px solid #28475d;border-radius:16px;padding:18px;margin:14px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.btn{display:inline-block;padding:10px 14px;border:0;border-radius:9px;background:#22c55e;color:#04130a;text-decoration:none;font-weight:bold}input,select,textarea{width:100%;box-sizing:border-box;padding:10px;margin:5px 0;background:#081925;color:white;border:1px solid #36586e;border-radius:8px}textarea{min-height:100px}.muted{color:#9fb4c4}.warn{background:#f59e0b;color:#231500;padding:12px;border-radius:10px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #28475d;text-align:right}.nav a{color:white;margin-left:12px}</style><body><div class="w">'+b+'</div></body></html>')
def nav():return '<div class="nav"><a href="/sales-center">مركز المبيعات</a><a href="/sales-actions">إجراءات الردود</a><a href="/quotes">عروض الأسعار</a><a href="/outbound">الرسائل</a></div>'
def qnum(qid):return 'ATQ-'+utcnow().strftime('%Y%m%d')+'-'+str(qid).zfill(4)
def commercial_total(q):return (q.get('total_with_vat') or q.get('sell_price') or 0)
def quote_text(q,company):
 return ('عرض سعر أولي – آفاق طويق\n\nالعميل: '+company+'\nرقم العرض: '+q['quote_number']+'\nالخدمة: '+q['service_type']+'\nالمسار: '+(q.get('origin') or '—')+' → '+(q.get('destination') or '—')+'\nالبضاعة: '+(q.get('cargo_description') or '—')+'\nالكمية/الوصف الكمي: '+(q.get('quantity') or '—')+'\n\nالقيمة قبل الضريبة: '+format((q.get('total_before_vat') or q.get('sell_price') or 0),',.2f')+' '+q['currency']+'\nالضريبة: '+format((q.get('vat_amount') or 0),',.2f')+' '+q['currency']+'\nالإجمالي: '+format(commercial_total(q),',.2f')+' '+q['currency']+'\nالصلاحية حتى: '+str(q.get('valid_until') or 'غير محدد')+'\n\nالافتراضات:\n'+(q.get('assumptions') or '—')+'\n\nالاستثناءات:\n'+(q.get('exclusions') or '—')+'\n\nملاحظة: يخضع العرض للمراجعة النهائية واعتماد آفاق طويق قبل الإرسال.')
@router.get('/quotes')
def home(request:Request):
 auth(request);data=rows('SELECT q.*,o.company_name FROM sales_quotes q JOIN opportunities o ON o.id=q.opportunity_id ORDER BY q.id DESC');trs=''.join('<tr><td>'+esc(x['quote_number'])+'</td><td>'+esc(x['company_name'])+'</td><td>'+esc(x['service_type'])+'</td><td>'+format(commercial_total(x),',.2f')+' '+esc(x['currency'])+'</td><td>'+esc(x['status'])+'</td><td><a class="btn" href="/quotes/'+str(x['id'])+'">فتح</a></td></tr>' for x in data);return shell(nav()+'<h1>Quote Builder — آفاق طويق</h1><div class="card muted">الأسعار والتكاليف تُدخل يدويًا. النظام لا يخترع تكلفة، ويمنع إرسال الهامش الأقل من الحد الإداري قبل الموافقة.</div><div class="card"><table><tr><th>رقم العرض</th><th>العميل</th><th>الخدمة</th><th>الإجمالي</th><th>الحالة</th><th></th></tr>'+trs+'</table></div>')
@router.get('/quotes/new/{oid}')
def new_quote(oid:int,request:Request,response_action_id:int|None=None):
 auth(request);o=one('SELECT * FROM opportunities WHERE id=?',(oid,));intel=one('SELECT * FROM opportunity_intelligence WHERE opportunity_id=?',(oid,))
 if not o:raise HTTPException(404)
 services=(intel or {}).get('services') or 'الخدمات اللوجستية';b=nav()+'<h1>إنشاء عرض سعر — '+esc(o['company_name'])+'</h1><form method="post" action="/quotes/create"><input type="hidden" name="opportunity_id" value="'+str(oid)+'"><input type="hidden" name="response_action_id" value="'+esc(response_action_id or '')+'"><div class="grid"><select name="service_type"><option>تخليص جمركي</option><option>نقل</option><option>شحن</option><option>تخزين</option><option>Door-to-Door</option><option>حل لوجستي متكامل</option></select><input name="origin" placeholder="من / Origin"><input name="destination" placeholder="إلى / Destination"><input name="cargo_description" placeholder="وصف البضاعة"><input name="quantity" placeholder="الكمية/الوزن/الحاويات"><select name="currency"><option>SAR</option><option>AED</option><option>USD</option></select><input name="base_cost" type="number" min="0" step="0.01" placeholder="تكلفة أولية" required><input name="margin_percent" type="number" min="0" step="0.01" placeholder="هامش الربح %" required><input name="valid_until" type="date"></div><textarea name="assumptions" placeholder="الافتراضات"></textarea><textarea name="exclusions" placeholder="الاستثناءات"></textarea><div class="card">الخدمات المرصودة من Intelligence: '+esc(services)+'</div><button class="btn">إنشاء العرض</button></form>'
 return shell(b)
@router.post('/quotes/create')
async def create(request:Request):
 s=auth(request);d=parse(await request.body());oid=int(d['opportunity_id']);cost=float(d.get('base_cost') or 0);margin=float(d.get('margin_percent') or 0);sell=round(cost*(1+margin/100),2);now=utcnow();qid=execute('INSERT INTO sales_quotes(opportunity_id,response_action_id,quote_number,status,service_type,origin,destination,cargo_description,quantity,currency,base_cost,margin_percent,sell_price,valid_until,assumptions,exclusions,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(oid,int(d['response_action_id']) if d.get('response_action_id') else None,'PENDING','draft',d.get('service_type'),d.get('origin'),d.get('destination'),d.get('cargo_description'),d.get('quantity'),d.get('currency','SAR'),cost,margin,sell,d.get('valid_until') or None,d.get('assumptions'),d.get('exclusions'),s['user_id'],now,now));num=qnum(qid);execute('UPDATE sales_quotes SET quote_number=? WHERE id=?',(num,qid));log(s['user_id'],'create_sales_quote','sales_quote',qid,'Quote created from operator-entered cost and margin');return RedirectResponse('/quotes/'+str(qid)+'/pricing',303)
@router.get('/quotes/{qid}')
def detail(qid:int,request:Request):
 auth(request);q=one('SELECT q.*,o.company_name FROM sales_quotes q JOIN opportunities o ON o.id=q.opportunity_id WHERE q.id=?',(qid,))
 if not q:raise HTTPException(404)
 approval=one('SELECT status FROM approvals WHERE id=?',(q.get('pricing_approval_id'),)) if q.get('pricing_approval_id') else None;blocked=bool(q.get('requires_manager_approval') and (not approval or approval['status']!='approved'));text=quote_text(q,q['company_name']);gate='<div class="warn">هذا العرض بهامش أقل من الحد الأدنى ويحتاج موافقة الإدارة قبل تحويله إلى رسالة.</div>' if blocked else ''
 action='<form method="post" action="/quotes/'+str(qid)+'/to-outbound"><button class="btn">تحويل العرض إلى مسودة رسالة للمراجعة</button></form>' if not blocked else ''
 b=nav()+'<h1>'+esc(q['quote_number'])+'</h1><div class="grid"><div class="card"><b>العميل</b><h2>'+esc(q['company_name'])+'</h2></div><div class="card"><b>الخدمة</b><h2>'+esc(q['service_type'])+'</h2></div><div class="card"><b>التكلفة الداخلية</b><h2>'+format(q['base_cost'],',.2f')+' '+esc(q['currency'])+'</h2></div><div class="card"><b>الهامش</b><h2>'+format(q['margin_percent'],'.2f')+'%</h2></div><div class="card"><b>إجمالي العميل</b><h2>'+format(commercial_total(q),',.2f')+' '+esc(q['currency'])+'</h2></div></div>'+gate+'<div class="card"><pre style="white-space:pre-wrap">'+esc(text)+'</pre></div><a class="btn" href="/quotes/'+str(qid)+'/pricing">إدارة بنود التكلفة والهامش وVAT</a> <a class="btn" target="_blank" href="/quotes/'+str(qid)+'/print">طباعة / حفظ PDF</a>'+action+'<div class="card muted">لا إرسال قبل المراجعة والموافقة البشرية. التكاليف الداخلية لا تظهر في النسخة التجارية.</div>'
 return shell(b)
@router.post('/quotes/{qid}/to-outbound')
def to_outbound(qid:int,request:Request):
 s=auth(request);q=one('SELECT q.*,o.company_name FROM sales_quotes q JOIN opportunities o ON o.id=q.opportunity_id WHERE q.id=?',(qid,))
 if not q:raise HTTPException(404)
 if q.get('requires_manager_approval'):
  a=one('SELECT * FROM approvals WHERE id=?',(q.get('pricing_approval_id'),)) if q.get('pricing_approval_id') else None
  if not a or a['status']!='approved':raise HTTPException(409,'Low margin quote requires manager approval before outbound draft')
 contact=one('SELECT email FROM sales_contacts WHERE opportunity_id=? AND verified=1 AND email IS NOT NULL ORDER BY id DESC LIMIT 1',(q['opportunity_id'],));recipient=(contact or {}).get('email');body='مرحبًا،\n\nنرفق لكم العرض الأولي من آفاق طويق بناءً على نطاق العمل الذي تمت مراجعته داخليًا.\n\nيرجى مراجعة التفاصيل أدناه، ويسعدنا تحديث العرض عند تغير نطاق العمل.\n\nمع التحية،\nآفاق طويق';proposal=quote_text(q,q['company_name']);now=utcnow();mid=execute('INSERT INTO outbound_messages(opportunity_id,channel,recipient,subject,body,proposal_text,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)',(q['opportunity_id'],'email',recipient,'عرض سعر '+q['quote_number']+' — آفاق طويق',body,proposal,'draft',s['user_id'],now,now));execute('UPDATE sales_quotes SET status=?,updated_at=? WHERE id=?',('draft_ready',now,qid));execute('UPDATE opportunities SET stage=?,estimated_value=?,currency=?,updated_at=? WHERE id=?',('proposal',commercial_total(q),q['currency'],now,q['opportunity_id']));log(s['user_id'],'quote_to_outbound','sales_quote',qid,'Approved pricing quote converted to outbound draft; no send');return RedirectResponse('/outbound/'+str(mid),303)
@router.get('/api/v7/quotes')
def api(request:Request):
 auth(request);return {'quotes':rows('SELECT id,opportunity_id,quote_number,status,service_type,currency,base_cost,margin_percent,sell_price,total_with_vat,requires_manager_approval,pricing_approval_id,valid_until,created_at FROM sales_quotes ORDER BY id DESC')}
